<!DOCTYPE html>
<html>
  	<head>
		<meta charset="UTF-8">
		<title>Error | Contact Organiser</title>
		<link rel="stylesheet" href="https://build.origami.ft.com/v2/bundles/css?modules=o-header@^4.0.0,o-table@^3.0.1,o-buttons@^3.0.3" />

	    <style type="text/css">
	      	body {
				margin:0;
			}
			h1 {
				text-align: center;
			}
  		</style>


  	</head>
	<body>
		<header data-o-component="o-header" class="o-header o-header--tall">
			<div class="o-header__container">
				<div class="o-header__primary">
					<div class="o-header__primary__left">
						<a href="/" class="o-header__logo o-header__logo--ft">
							<abbr title="Financial Times">FT</abbr>
							<h1 class="o-header__title">Contact Organiser</h1>
						</a>
					</div>
					<div class="o-header__primary__center"><h3 class="o-header__tagline">Organising the Custodians of our Systems</h3>
					</div>
				</div>
			</div>
		</header>

		<h1>
			Error: {{message}}
		</h1>
		<script src="https://build.origami.ft.com/v2/bundles/js?modules=o-techdocs@^5.0.1,o-table@^3.0.1,o-buttons@^3.0.3,o-forms@^2.0.0"></script>
	</body>
</html>
